language: android
os: linux
dist: trusty
language: python
python:
    - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
script: ./scripts/make-device.sh
