language: android
dist: xenial
before install: 
- sudo apt-get update
- sudo apt-get -y install openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev
- chmod u+x bash build-twrp.sh
android:
  components:
  - platform-tools
  - build-tools-29.0.0
  - extra
  
