sudo: true
language: android
os: linux
dist: trusty

install:
  - sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python
  - sudo apt-get install -y sudo apt-get install git ccache automake lzop bison gperf build-essential zip curl zlib1g-dev zlib1g-dev:i386 g++-multilib python-networkx libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng  

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
jdk:
  - openjdk8
- os: linux
cache: ccache
compiler:
  - clang
  - gcc
addons:
  apt:
    update: true
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - oracle-java8-installer
      - clang-5.0
env:
  - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
  global:
    - MAKEFLAGS="-j 2"
sudo: false
script:
  - jdk_switcher use openjdk8
  - while sleep 9m; do echo "=====[ $SECONDS seconds build still running ]====="; done &
  - bash build-twrp.sh
before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d-%H%M')}
  - export RELEASE_NAME=TWRP-Realme-3
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: Y27fkgkVnS1+fQmjaqMpVeW1caFz/dZ25dpPivV10CWbpmLAY0VId2sdU5pCpdkEKcs+mgbOp0EXBmtTyn5Hcnik3tHcj77+pQBdS5+8Og/LM19TUlgGwLSCJpSpracKF1SaJA5x/gtR2YxlQtox7AWwhUJc/3BMfrpHy88PBgHt3Wzv1WiRoPr5H3pts59OTjADFRNzU96dVD2XAvGmMSsNO3cTNZwfrQpOnx30ho7dEWEhs6DpgPUjkTDCNvjlqIzhkuY0JAxnp1IC8VZ/kKxM+RByTI3FBvnSvntNdPYYOyV1Y3dVlXKTM25EtQh11lKyRBpAuWfnYrlTh4/1haB4PluE8ShAH0zu2/Z6UGdXWY66usdy7gVHGsh2haI+w8GhixSJu6OnK/21cAfvqR9JoJPGtdkjjzjzAMwNcFfYPu5GWV20QVBhdN12XnsCsDuFu3sgJGFiHgo3z49cUeF1rNbKhR26+y/1iB/c2XUJCwnIVYbX2UbQRLPixoCFrdS2IxHHFarX+LbYVHCpGCBUqJ1PrLmf7m9TLqDA+JRZZuyXz0LAliK2qRwfS2dO8aHyfkkyZ26YAe1SxBtMXY/cGImB4iJoEkFM1B/QDLGav+7N8blHFgSkBpan2DSocfgZUd6k/Cc9vSbVtanMRgAr0I4bOpPublG/DJetLl0=
  name: ${RELEASE_NAME}
  file_glob: true
  file: /home/travis/twrp/out/target/product/a12/recovery.img
  skip_cleanup: true
  on:
    repo: edward0181/android_device_samsung_a12
    branch: twrp-11

script: ./build-twrp.sh
