language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-29.0.0

  script:
   - bash build-twrp.sh
   
before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d-%H%M')}
  - export RELEASE_NAME=TWRP-a12-3
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
