sudo: required
services:
 - docker
before_install:
 - docker pull surendrajat/twrp-builder:latest
before_script:
 - cd $HOME && mkdir twrp
 - cd $HOME/twrp/
 - repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
 - repo sync --no-repo-verify -c --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune -jnproc
script:
 - cd $HOME/twrp/ && git clone https://github.com/edward0181/android_device_samsung_a12 -b twrp-11.0 device/samsung/a12
 - git clone https://github.com/00p513-dev/android_kernel_samsung_a12.git kernel/samsung/a12
 
 - |
   docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
   cd /root/twrp
   source build/envsetup.sh && lunch twrp_a12-eng && make -j16 recoveryimage
   exit
   EOF
